"""Loopback Browser Companion for a real ChatGPT Web conversation.

Security boundary:
- listens only on 127.0.0.1;
- pairing uses a short-lived one-time code generated by ORDAX;
- the long bearer token is returned only to the extension service worker;
- page content scripts never receive the bearer token;
- commands are limited to ChatGPT conversation text exchange, never local files/tools.
"""
from __future__ import annotations

import json
import secrets
import sqlite3
import threading
import time
import uuid
from contextlib import contextmanager
from dataclasses import dataclass
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from .auth import resolve_chat_app_state_dir


_PROTOCOL = 1
_PAIR_TTL_SECONDS = 10 * 60
_TOKEN_BYTES = 32
_MAX_BODY = 2 * 1024 * 1024
_ALLOWED_HOSTS = {"chatgpt.com", "chat.openai.com"}


def _now() -> float:
    return time.time()


def _conversation_id(url: str) -> str | None:
    try:
        parsed = urlsplit(str(url or ""))
    except ValueError:
        return None
    host = (parsed.hostname or "").lower()
    if host not in _ALLOWED_HOSTS:
        return None
    parts = [part for part in parsed.path.split("/") if part]
    if len(parts) >= 2 and parts[0] == "c" and len(parts[1]) >= 8:
        return parts[1][:160]
    return None


class BrowserCompanionStore:
    def __init__(self, path: str | Path | None = None):
        self.path = (
            Path(path).expanduser().resolve()
            if path
            else resolve_chat_app_state_dir() / "browser-companion.db"
        )
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self._init_schema()

    @contextmanager
    def connect(self):
        connection = sqlite3.connect(self.path, timeout=10)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA journal_mode=WAL")
        try:
            yield connection
            connection.commit()
        finally:
            connection.close()

    def _init_schema(self) -> None:
        with self.connect() as connection:
            connection.executescript(
                """
                CREATE TABLE IF NOT EXISTS browser_conversations(
                  id TEXT PRIMARY KEY,
                  url TEXT NOT NULL,
                  title TEXT,
                  browser_id TEXT,
                  updated_at REAL NOT NULL
                );
                CREATE TABLE IF NOT EXISTS browser_messages(
                  conversation_id TEXT NOT NULL,
                  message_key TEXT NOT NULL,
                  role TEXT NOT NULL,
                  text TEXT NOT NULL,
                  observed_at REAL NOT NULL,
                  PRIMARY KEY(conversation_id, message_key)
                );
                CREATE TABLE IF NOT EXISTS browser_commands(
                  id TEXT PRIMARY KEY,
                  conversation_id TEXT NOT NULL,
                  text TEXT NOT NULL,
                  state TEXT NOT NULL,
                  created_at REAL NOT NULL,
                  delivered_at REAL,
                  ack_at REAL,
                  error TEXT
                );
                CREATE INDEX IF NOT EXISTS idx_browser_commands_pending
                  ON browser_commands(state, conversation_id, created_at);
                """
            )

    def observe(
        self,
        *,
        conversation_id: str,
        url: str,
        title: str,
        browser_id: str,
        messages: list[dict[str, Any]],
    ) -> dict[str, Any]:
        now = _now()
        with self.connect() as connection:
            connection.execute(
                """
                INSERT INTO browser_conversations(id,url,title,browser_id,updated_at)
                VALUES(?,?,?,?,?)
                ON CONFLICT(id) DO UPDATE SET
                  url=excluded.url,
                  title=excluded.title,
                  browser_id=excluded.browser_id,
                  updated_at=excluded.updated_at
                """,
                (conversation_id, url, title[:500], browser_id[:128], now),
            )
            accepted = 0
            for item in messages[:400]:
                key = str(item.get("key") or "").strip()[:300]
                role = str(item.get("role") or "").strip()
                text = str(item.get("text") or "")
                if not key or role not in {"user", "assistant"} or not text:
                    continue
                connection.execute(
                    """
                    INSERT INTO browser_messages(
                      conversation_id,message_key,role,text,observed_at
                    ) VALUES(?,?,?,?,?)
                    ON CONFLICT(conversation_id,message_key) DO UPDATE SET
                      role=excluded.role,
                      text=excluded.text,
                      observed_at=excluded.observed_at
                    """,
                    (conversation_id, key, role, text[:500_000], now),
                )
                accepted += 1
        return {"conversation_id": conversation_id, "accepted": accepted}

    def conversations(self, *, limit: int = 100) -> list[dict[str, Any]]:
        with self.connect() as connection:
            rows = connection.execute(
                """
                SELECT c.*,
                  (SELECT COUNT(*) FROM browser_messages m WHERE m.conversation_id=c.id) AS message_count
                FROM browser_conversations c
                ORDER BY updated_at DESC LIMIT ?
                """,
                (max(1, min(500, int(limit))),),
            ).fetchall()
        return [dict(row) for row in rows]

    def messages(self, conversation_id: str, *, limit: int = 500) -> list[dict[str, Any]]:
        with self.connect() as connection:
            rows = connection.execute(
                """
                SELECT message_key AS key, role, text, observed_at
                FROM browser_messages
                WHERE conversation_id=?
                ORDER BY observed_at ASC, rowid ASC LIMIT ?
                """,
                (conversation_id, max(1, min(2000, int(limit)))),
            ).fetchall()
        return [dict(row) for row in rows]

    def enqueue(self, conversation_id: str, text: str) -> dict[str, Any]:
        text = str(text or "").strip()
        if not text:
            raise ValueError("message text is required")
        command_id = str(uuid.uuid4())
        created = _now()
        with self.connect() as connection:
            known = connection.execute(
                "SELECT 1 FROM browser_conversations WHERE id=?",
                (conversation_id,),
            ).fetchone()
            if not known:
                raise ValueError("conversation is not attached to ORDAX")
            connection.execute(
                """
                INSERT INTO browser_commands(id,conversation_id,text,state,created_at)
                VALUES(?,?,?,?,?)
                """,
                (command_id, conversation_id, text[:200_000], "queued", created),
            )
        return {
            "id": command_id,
            "conversation_id": conversation_id,
            "text": text,
            "state": "queued",
            "created_at": created,
        }

    def pull(self, conversation_id: str, *, limit: int = 5) -> list[dict[str, Any]]:
        now = _now()
        with self.connect() as connection:
            rows = connection.execute(
                """
                SELECT * FROM browser_commands
                WHERE conversation_id=? AND state='queued'
                ORDER BY created_at ASC LIMIT ?
                """,
                (conversation_id, max(1, min(20, int(limit)))),
            ).fetchall()
            ids = [str(row["id"]) for row in rows]
            if ids:
                placeholders = ",".join("?" for _ in ids)
                connection.execute(
                    f"UPDATE browser_commands SET state='delivered', delivered_at=? WHERE id IN ({placeholders})",
                    (now, *ids),
                )
        return [
            {
                "id": row["id"],
                "conversation_id": row["conversation_id"],
                "text": row["text"],
                "state": "delivered",
                "created_at": row["created_at"],
            }
            for row in rows
        ]

    def ack(self, command_id: str, *, ok: bool, error: str = "") -> dict[str, Any]:
        now = _now()
        state = "sent" if ok else "failed"
        with self.connect() as connection:
            row = connection.execute(
                "SELECT * FROM browser_commands WHERE id=?",
                (command_id,),
            ).fetchone()
            if not row:
                raise ValueError("command not found")
            connection.execute(
                """
                UPDATE browser_commands SET state=?, ack_at=?, error=? WHERE id=?
                """,
                (state, now, (error or None), command_id),
            )
        return {"id": command_id, "state": state, "ack_at": now, "error": error or None}


@dataclass
class PairingState:
    code: str
    expires_at: float


class BrowserCompanionServer:
    def __init__(
        self,
        *,
        store: BrowserCompanionStore | None = None,
        host: str = "127.0.0.1",
        port: int = 8775,
    ):
        self.store = store or BrowserCompanionStore()
        self.host = host
        self.port = int(port)
        self._server: ThreadingHTTPServer | None = None
        self._thread: threading.Thread | None = None
        self._pairing: PairingState | None = None
        self._tokens: set[str] = set()
        self._lock = threading.RLock()

    def start(self) -> dict[str, Any]:
        with self._lock:
            if self._server is not None:
                return self.status()
            outer = self

            class Handler(BaseHTTPRequestHandler):
                server_version = "ORDAXBrowserCompanion/1"

                def log_message(self, _format, *_args):
                    return

                def _json(self, status: int, payload: dict[str, Any]):
                    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
                    self.send_response(status)
                    self.send_header("Content-Type", "application/json; charset=utf-8")
                    self.send_header("Content-Length", str(len(body)))
                    self.send_header("Cache-Control", "no-store")
                    self.send_header("Access-Control-Allow-Origin", "*")
                    self.send_header("Access-Control-Allow-Headers", "authorization, content-type")
                    self.send_header("Access-Control-Allow-Methods", "GET,POST,OPTIONS")
                    self.end_headers()
                    self.wfile.write(body)

                def do_OPTIONS(self):
                    self._json(200, {"ok": True})

                def _read(self) -> dict[str, Any]:
                    try:
                        length = int(self.headers.get("Content-Length") or 0)
                    except ValueError:
                        length = 0
                    if length < 0 or length > _MAX_BODY:
                        raise ValueError("request body is too large")
                    raw = self.rfile.read(length) if length else b"{}"
                    payload = json.loads(raw.decode("utf-8"))
                    if not isinstance(payload, dict):
                        raise ValueError("JSON object required")
                    return payload

                def _authorized(self) -> bool:
                    header = str(self.headers.get("Authorization") or "")
                    token = header[7:] if header.startswith("Bearer ") else ""
                    with outer._lock:
                        return bool(token and token in outer._tokens)

                def do_GET(self):
                    parsed = urlsplit(self.path)
                    if parsed.path == "/hello":
                        self._json(200, {
                            "ok": True,
                            "product": "ORDAX Dev Browser Companion",
                            "protocol": _PROTOCOL,
                            "pair_required": True,
                        })
                        return
                    if parsed.path == "/commands":
                        if not self._authorized():
                            self._json(401, {"ok": False, "error": "unauthorized"})
                            return
                        conversation = self.headers.get("X-ORDAX-Conversation") or ""
                        self._json(200, {
                            "ok": True,
                            "commands": outer.store.pull(str(conversation)),
                        })
                        return
                    self._json(404, {"ok": False, "error": "not_found"})

                def do_POST(self):
                    try:
                        payload = self._read()
                    except (ValueError, json.JSONDecodeError) as error:
                        self._json(400, {"ok": False, "error": str(error)})
                        return
                    parsed = urlsplit(self.path)
                    if parsed.path == "/pair":
                        code = str(payload.get("code") or "").strip()
                        browser_id = str(payload.get("browser_id") or "").strip()
                        with outer._lock:
                            pairing = outer._pairing
                            if (
                                pairing is None
                                or pairing.expires_at < _now()
                                or not secrets.compare_digest(pairing.code, code)
                            ):
                                self._json(403, {"ok": False, "error": "invalid_or_expired_pairing_code"})
                                return
                            token = secrets.token_urlsafe(_TOKEN_BYTES)
                            outer._tokens.add(token)
                            outer._pairing = None
                        self._json(200, {
                            "ok": True,
                            "token": token,
                            "protocol": _PROTOCOL,
                            "browser_id": browser_id[:128],
                        })
                        return
                    if not self._authorized():
                        self._json(401, {"ok": False, "error": "unauthorized"})
                        return
                    if parsed.path == "/events":
                        url = str(payload.get("url") or "")
                        conversation = _conversation_id(url)
                        if not conversation:
                            self._json(400, {"ok": False, "error": "unsupported_chatgpt_conversation_url"})
                            return
                        result = outer.store.observe(
                            conversation_id=conversation,
                            url=url,
                            title=str(payload.get("title") or ""),
                            browser_id=str(payload.get("browser_id") or ""),
                            messages=payload.get("messages") if isinstance(payload.get("messages"), list) else [],
                        )
                        self._json(200, {"ok": True, **result})
                        return
                    if parsed.path == "/commands/ack":
                        try:
                            result = outer.store.ack(
                                str(payload.get("id") or ""),
                                ok=bool(payload.get("ok")),
                                error=str(payload.get("error") or ""),
                            )
                        except ValueError as error:
                            self._json(404, {"ok": False, "error": str(error)})
                            return
                        self._json(200, {"ok": True, **result})
                        return
                    self._json(404, {"ok": False, "error": "not_found"})

            self._server = ThreadingHTTPServer((self.host, self.port), Handler)
            self._thread = threading.Thread(
                target=self._server.serve_forever,
                name="ordax-browser-companion",
                daemon=True,
            )
            self._thread.start()
            self.port = int(self._server.server_port)
            return self.status()

    def stop(self) -> dict[str, Any]:
        with self._lock:
            server = self._server
            thread = self._thread
            self._server = None
            self._thread = None
            self._tokens.clear()
            self._pairing = None
        if server is not None:
            server.shutdown()
            server.server_close()
        if thread is not None:
            thread.join(timeout=3)
        return self.status()

    def new_pairing_code(self) -> dict[str, Any]:
        self.start()
        code = f"{secrets.randbelow(10**8):08d}"
        expires_at = _now() + _PAIR_TTL_SECONDS
        with self._lock:
            self._pairing = PairingState(code=code, expires_at=expires_at)
        return {
            "code": code,
            "expires_at": expires_at,
            "port": self.port,
            "protocol": _PROTOCOL,
        }

    def status(self) -> dict[str, Any]:
        with self._lock:
            pairing = self._pairing
            return {
                "running": self._server is not None,
                "host": self.host,
                "port": self.port,
                "protocol": _PROTOCOL,
                "paired_clients": len(self._tokens),
                "pairing_active": bool(pairing and pairing.expires_at >= _now()),
                "pairing_expires_at": pairing.expires_at if pairing else None,
                "conversations": len(self.store.conversations(limit=500)),
            }

    def conversations(self) -> list[dict[str, Any]]:
        return self.store.conversations()

    def messages(self, conversation_id: str) -> list[dict[str, Any]]:
        return self.store.messages(conversation_id)

    def send(self, conversation_id: str, text: str) -> dict[str, Any]:
        return self.store.enqueue(conversation_id, text)
