import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
import {
  Drawer,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
} from "@/components/ui/drawer";
import { HumanGamePlanView } from "@/components/ordax/HumanGamePlanView";
import type { EngineGapReport } from "@/lib/ordax/human-game-plan";

export type GamePlanResult = {
  plan: unknown;
  planWarnings?: string[];
  planDiff?: {
    autoAddedSystems?: string[];
    autoAddedEntities?: string[];
    coreLoopAutoGenerated?: boolean;
    loopTypeAutoFixed?: boolean;
    lifecycle?: {
      autoAddedStates?: string[];
      autoAddedTransitions?: string[];
      autoAddedUI?: string[];
      autoAddedControls?: string[];
      requiredSignalsAnyOfAutoAdded?: boolean;
      signalAutoChosen?: boolean;
      startConditionAutoAdded?: boolean;
      loseConditionAutoAdded?: boolean;
      winConditionAutoAdded?: boolean;
      scoreRuleAutoAdded?: boolean;
    };
  };
  engineGapReport?: EngineGapReport;
};

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  data: GamePlanResult | null;
  onAccept: () => void;
  accepting?: boolean;
};

export function PlanReviewDrawer({ open, onOpenChange, data, onAccept, accepting }: Props) {
  const planText = data?.plan ? JSON.stringify(data.plan, null, 2) : "";
  const autoSystems = data?.planDiff?.autoAddedSystems ?? [];
  const autoEntities = data?.planDiff?.autoAddedEntities ?? [];
  const lifecycle = data?.planDiff?.lifecycle;
  const lifecycleStates = lifecycle?.autoAddedStates ?? [];
  const lifecycleTransitions = lifecycle?.autoAddedTransitions ?? [];
  const lifecycleUI = lifecycle?.autoAddedUI ?? [];
  const lifecycleControls = lifecycle?.autoAddedControls ?? [];
  const warnings = data?.planWarnings ?? [];
  const [showJson, setShowJson] = useState(false);

  const humanKey = useMemo(() => {
    try {
      return JSON.stringify({ plan: data?.plan, planDiff: data?.planDiff, warnings: data?.planWarnings }).length;
    } catch {
      return Date.now();
    }
  }, [data?.plan, data?.planDiff, data?.planWarnings]);

  return (
    <Drawer open={open} onOpenChange={onOpenChange}>
      <DrawerContent className="max-h-[85vh]">
        <DrawerHeader>
          <div className="flex items-start justify-between gap-3">
            <div>
              <DrawerTitle>GAME_PLAN (NEW_GAME)</DrawerTitle>
              <DrawerDescription>
                Revise o plano humano. Ao aceitar, o runtimeSpec será gerado a partir deste contrato.
              </DrawerDescription>
            </div>
            <label className="flex items-center gap-2 text-xs text-muted-foreground select-none">
              <span>Ver JSON técnico</span>
              <Switch checked={showJson} onCheckedChange={setShowJson} />
            </label>
          </div>
        </DrawerHeader>

        <div className="px-4 pb-2">
          <div className="grid gap-3">
            {(autoSystems.length > 0 || autoEntities.length > 0) && (
              <div className="rounded-md border border-border/50 bg-muted/10 p-3">
                <div className="text-xs font-semibold">Auto-adicionado (diff)</div>
                <Separator className="my-2" />
                {autoSystems.length > 0 && (
                  <div className="text-xs">
                    <div className="font-medium">Systems</div>
                    <div className="mt-1 text-muted-foreground">{autoSystems.join(", ")}</div>
                  </div>
                )}
                {autoEntities.length > 0 && (
                  <div className="mt-2 text-xs">
                    <div className="font-medium">Entities</div>
                    <div className="mt-1 text-muted-foreground">{autoEntities.join(", ")}</div>
                  </div>
                )}
              </div>
            )}

            {(lifecycleStates.length > 0 || lifecycleTransitions.length > 0 || lifecycleUI.length > 0 || lifecycleControls.length > 0) && (
              <div className="rounded-md border border-border/50 bg-muted/10 p-3">
                <div className="text-xs font-semibold">Lifecycle (diff)</div>
                <Separator className="my-2" />

                {lifecycleStates.length > 0 && (
                  <div className="text-xs">
                    <div className="font-medium">States</div>
                    <div className="mt-1 text-muted-foreground">{lifecycleStates.join(", ")}</div>
                  </div>
                )}

                {lifecycleTransitions.length > 0 && (
                  <div className="mt-2 text-xs">
                    <div className="font-medium">Transitions</div>
                    <div className="mt-1 text-muted-foreground">{lifecycleTransitions.join(", ")}</div>
                  </div>
                )}

                {lifecycleUI.length > 0 && (
                  <div className="mt-2 text-xs">
                    <div className="font-medium">UI</div>
                    <div className="mt-1 text-muted-foreground">{lifecycleUI.join(", ")}</div>
                  </div>
                )}

                {lifecycleControls.length > 0 && (
                  <div className="mt-2 text-xs">
                    <div className="font-medium">Controls</div>
                    <div className="mt-1 text-muted-foreground">{lifecycleControls.join(", ")}</div>
                  </div>
                )}
              </div>
            )}

            {warnings.length > 0 && (
              <div className="rounded-md border border-border/50 bg-muted/10 p-3">
                <div className="text-xs font-semibold">Avisos</div>
                <Separator className="my-2" />
                <ul className="list-disc pl-4 text-xs text-muted-foreground space-y-1">
                  {warnings.slice(0, 24).map((w, i) => (
                    <li key={i}>{w}</li>
                  ))}
                </ul>
              </div>
            )}

            {showJson ? (
              <div className="rounded-md border border-border/50 bg-background/10">
                <div className="px-3 py-2 text-xs font-semibold">Plano (JSON técnico)</div>
                <Separator />
                <ScrollArea className="h-[42vh]">
                  <pre className="p-3 text-[11px] leading-relaxed whitespace-pre-wrap break-words">{planText || "(vazio)"}</pre>
                </ScrollArea>
              </div>
            ) : (
              <HumanGamePlanView
                key={humanKey}
                plan={data?.plan}
                planDiff={data?.planDiff}
                warnings={data?.planWarnings}
                engineGapReport={data?.engineGapReport}
              />
            )}
          </div>
        </div>

        <DrawerFooter>
          <Button onClick={onAccept} disabled={!data?.plan || accepting}>
            {accepting ? "Gerando runtimeSpec…" : "Aceitar e gerar runtimeSpec"}
          </Button>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={accepting}>
            Cancelar
          </Button>
        </DrawerFooter>
      </DrawerContent>
    </Drawer>
  );
}
